## 에러의 종류

1. 컴파일 에러 : 컴파일 시에 발생하는 에러
2. 런타임 에러 : 실행 시에 발생하는 에러
3. 논리적 에러 : 실행이 되는데 의도와 다르게 동작하는 경우

런타임 에러를 두가지로 구분한다.
1. 에러 : 코드에 의해서 수습될 수 없는 심각한 오류
2. 예외 : 코드에 의해서 수습할 수 있는 미약한 오류


## 예외 클래스 구조
모든 예외의 최고 조상은  `Exception` 클래스이며 그 안에 `RuntimeException`가 있다.
예외 클래스는 크게 위 두개로 나뉜다.

`RuntimeException`클래스는 주로 프로그래머의 실수에 의해 발생 할 수 있는 예외들과 관련있고,
`Exception`클래스는 주로 외부의 영향(사용자의 실수)으로 발생 할 수 있는 예외들과 관련있다.

## 예외처리하기 
### try-catch 구문
```java
try{
	//예외가 발생할 가능성이 있는 코드
}catch(Exception1 e1){
	//Exception1 예외가 발생했을 경우 처리하는 코드
}catch(Exception2 e2){
	//Exception2 예외가 발생했을 경우 처리하는 코드
}
```
#### 에러예시
```java
class ExceptionEx2 {
	public static void main(String args[]) {
		int number = 100;
		int result = 0;

		for(int i=0; i < 10; i++) {
			result = number / (int)(Math.random() * 10); // 7번째 라인, 0으로 나누게 되어 ArithmeticException이 발생 할 수 있음.
			System.out.println(result);
		}
	} 
}
```
결과
```
20
100
java.lang.ArithmeticException: / by zero at ExceptionEx2.main(ExceptionEx2.java:7) 
```
#### 예외처리
```java
class ExceptionEx3 {
	public static void main(String args[]) {
		int number = 100;
		int result = 0;

		for(int i=0; i < 10; i++) {
			try {// 에러가 생길수 있는 코드 입력
				result = number / (int)(Math.random() * 10);
				System.out.println(result); 
			} catch (ArithmeticException e)	{ // ArithmeticException이 발생되면 실행되는 코드
				System.out.println("0");	
			}  
		}
	} 
}
```

